import Head from "next/head";
import Header from "components/Layout/components/Header/Header";
import Footer from "components/Layout/components/Footer/Footer";

export default function Layout({ children }) {
  return (
    <>
      <Head>
        <title>The Sock Kingdom</title>
        <title>The Sock Kingdom</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main>{children}</main>
      <Footer />
    </>
  );
}
