import Head from "next/head";
import { Footer, Header } from "./components";

export default function Layout({ children }) {
  return (
    <>
      <Head>
        <title>The Sock Kingdom</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div id="app">
        <Header />
        <main>{children}</main>
        <Footer />
      </div>
    </>
  );
}
